### PR TITLE
Feat: some fix to support openid deployment

### LINKED ISSUE #245: The app does not work with openid and force_connect=false
The fetch method to get the dashboars is never call

### PR DESCRIPTION
**Pull request by mbarbet**
- Fix #245

### CODE REVIEW

File: src/app/components/card/card.component.ts [hunk 1]
```diff
@@ -52,13 +51,12 @@ export class CardComponent implements AfterViewInit, OnInit {
...
     @ViewChild('configMenu', {static: false}) public configMenu: ConfigMenuComponent;
     @Input() public card: Card;
-    @Input() public userGroups: string[] = [];
     @Input() public publicOrg = false;
     @Output() public actionOnCard: Subject<CardAction> = new Subject<CardAction>();
 
     public action = Action;
     public status: DashboardStatus = 'private';
-    public NO_ORGANISATION = NO_ORGANISATION;
+    public NO_ORGANISATION = '';
```
Comment (QuCMGisaia) [inline src/app/components/card/card.component.ts:59]: why this change?

**Review by QuCMGisaia — APPROVED** [review]

File: src/app/components/card/card.component.ts (hunk 1 above)
Comment (mbarbet) [reply src/app/components/card/card.component.ts:59]: NO_ORGANISATION variable in toolkit is 'no_organisation', if we use it, we retrieve no_organisation in an arlas-org-filter  header and we want not that in the openid case, we dont handle org for openid

**Review by MohamedHamouGisaia — APPROVED** [review]

File: src/app/components/dynamic-hub/dynamic-hub.component.ts [hunk 2]
```diff
@@ -289,6 +271,7 @@ export class DynamicHubComponent implements OnInit {
     private fetchAllCards() {
         this.permissionService.get('persist/resource/').subscribe((resources: Resource[]) => {
             this.canCreateDashboard = (resources.filter(r => r.verb === 'POST').length > 0);
+            this.cardService.canCreateDashboardByOrg.set('', resources.filter(r => r.verb === 'POST').length > 0);
```
Comment (sebbousquet) [inline src/app/components/dynamic-hub/dynamic-hub.component.ts:274]: There is duplication here, maybe we cant use the `map` from the service

File: src/app/components/dynamic-hub/dynamic-hub.component.ts [hunk 3]
```diff
@@ -262,6 +243,7 @@ export class DynamicHubComponent implements OnInit {
                 .pipe(
                     mergeMap((resources: Resource[]) => {
                         this.canCreateDashboardByOrg.set(o, resources.filter(r => r.verb === 'POST').length > 0);
+                        this.cardService.canCreateDashboardByOrg.set(o, resources.filter(r => r.verb === 'POST').length > 0);
```
Comment (sebbousquet) [inline src/app/components/dynamic-hub/dynamic-hub.component.ts:246]: There is duplication here, maybe we cant use the map from the service

**Comment by MohamedHamouGisaia** [comment]
@mbarbet it fixes #245 right ?

**Review by sebbousquet — APPROVED** [review]

File: src/app/components/card/card.component.ts (hunk 1 above)
Comment (QuCMGisaia) [reply src/app/components/card/card.component.ts:59]: Does that mean that with this modification it does not work anymore for IAM?
